name: Build XPI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and tag
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: bahmutov/npm-install@v1.6.0
      - name: Build XPI
        run: yarn build
      - name: Create release
        uses: softprops/action-gh-release@v0.1.13
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/elderly-mail.xpi

